version: 2


jobs:
  build:
      working_directory: /virgo
      docker:
        - image: golang:1.12.7-stretch
      steps:
        - checkout
        - run: |
            go build ./...

  release:
      working_directory: /virgo
      docker:
        - image: golang:1.12.7-stretch
      steps:
        - checkout
        - run: |
            go build 
            mv virgo virgo-$CIRCLE_TAG
            go run github.com/tcnksm/ghr -replace -token $GITKEY -username anastop -repository virgo $CIRCLE_TAG virgo-$CIRCLE_TAG
            

workflows:
  version: 2
  untagged-build:
    jobs:
      - build:        
          filters:
            tags:
              only: /^v.*/
  tagged-build:
    jobs:
      - release:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
